services:
  customer-service:
    build:
      context: ./customers
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://mongodb-dev:27017/car_sales_db
      - PORT=3001
      - APP_SECRET=jg_secret_key_super_secreta_123
    depends_on:
      - mongodb-dev

  product-service:
    build:
      context: ./products
    ports:
      - "3002:3002"
    environment:
      - DB_URL=mongodb://mongodb-dev:27017/car_sales_db
      - PORT=3002
      - APP_SECRET=jg_secret_key_super_secreta_123
    depends_on:
      - mongodb-dev

  shopping-service:
    build:
      context: ./shopping
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - APP_SECRET=jg_secret_key_super_secreta_123

  mongodb-dev:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
