services:
  product-service:
      container_name: c-product
      build: .
      restart: unless-stopped
      ports:
        - "8002:8002"
      environment:
        - DB_URL=mongodb://product-db:27017/products
        - PORT=8002
        - APP_SECRET=jg_secret_key_super_secreta_123
      volumes:
        - .:/app
        - /app/node_modules
      depends_on:
        product-db:
          condition: service_healthy
      networks:
        - microservices-network

  product-db:
    container_name: c-product-db
    image: mongo:7
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27020:27017"
    volumes:
      - product-data:/data/db

volumes:
  product-data:
